@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package forestry.api.lepidopterology;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
